USE [AdventureWorksLT2022]
GO

SELECT [CustomerID]
      ,[NameStyle]
      ,[Title]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Suffix]
      ,[CompanyName]
      ,[SalesPerson]
      ,[EmailAddress]
      ,[Phone]
      ,[PasswordHash]
      ,[PasswordSalt]
      ,[rowguid]
      ,[ModifiedDate]
  FROM [SalesLT].[Customer]

GO


SELECT CHARINDEX('o','Gourish');
SELECT CONCAT('Gourish','Bhagat');
SELECT CONCAT_WS('/','Gourish','Bhagat');
SELECT LEFT('GOURISHBHAGAT',7);
SELECT LEN('GOURISHBHAGAT');
SELECT LOWER('Gourish Bhagat');
SELECT LTRIM('         Gourish Bhagat');
SELECT FORMAT(getdate(),'d','en-US');
SELECT FORMAT(getdate(),'d','uk');
SELECT FORMAT(getdate(),'d','ind');
SELECT REPLACE('GOURISH','G','N');
SELECT REVERSE('GOURISH');
SELECT RIGHT('GOURISHBHAGAT',7);
SELECT RTRIM('GOURISH       ');
SELECT STR(36);
SELECT STUFF('GOURISHBHAGAT',1,3,'BHAGAT');
SELECT TRIM('GOURISHBHAGAT');
SELECT UPPER('gourish bhagat');
SELECT SUBSTRING('GOURISHBHAGAT',2,6);

SELECT AVG(Price) FROM PRODUCTS;
SELECT CEILING(25.25);
SELECT COUNT(PRODUCTID) FROM PRODUCTS;
SELECT FLOOR(25.25);
SELECT MAX(PRICE) FROM PRODUCT;
SELECT MIN(PRICE) FROM PRODUCT;
SELECT ROUND(228.402,2);
SELECT SQRT(64);
SELECT SUM (PRICE) FROM PRODUCTS;

SELECT GETDATE();
SELECT DATEADD(YEAR,1,GETDATE());
SELECT DATEDIFF(YEAR,'2023/06/25',GETDATE());
SELECT DATEFROMPARTS(2023,07,07);
SELECT DATEPART(YEAR,GETDATE());
SELECT ISDATE('2023-07-18');
SELECT MONTH(GETDATE());
SELECT YEAR(GETDATE());

SELECT CAST(26.28 AS INT);
SELECT COALESCE(NULL,'COZENTUS',NULL,'GOURISH');
SELECT CONVERT(INT, 25.28);
SELECT IIF(500>1000,'YES','NO');
SELECT ISNULL(NULL,'GOURISH');
SELECT NULLIF(25,26);